version: 2

sources:
  - name: staging
    database: dev
    schema: public

    tables:
      - name: bike_rental_data

models:
  - name: bike_rental_data
    description: ""
    columns:
      - name: id
        data_type: integer
        description: ""

      - name: number
        data_type: integer
        description: ""

      - name: start_date
        data_type: timestamp without time zone
        description: ""

      - name: start_station_number
        data_type: integer
        description: ""

      - name: start_station
        data_type: character varying
        description: ""

      - name: end_date
        data_type: timestamp without time zone
        description: ""

      - name: end_station_number
        data_type: integer
        description: ""

      - name: end_station
        data_type: character varying
        description: ""

      - name: bike_number
        data_type: integer
        description: ""

      - name: bike_model
        data_type: character varying
        description: ""

      - name: total_duration
        data_type: character varying
        description: ""

      - name: total_duration_ms
        data_type: integer
        description: ""